projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - operations/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: operations
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 4
